title: Xuanya Zhu
# position:
# affiliation:
# email:
google_scholar: https://scholar.google.com/
github_link: https://github.com/12zxyu
linkedin: https://www.linkedin.com/in/adamxyzhu/
# google_analytics:
description: Minimal is a theme for GitHub Pages.
theme: jekyll-theme-minimal